version: 2
jobs:
  build:
    docker:
      - image: debian:stretch-slim
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: >
            apt-get update &&
            apt-get install -y
            g++
            cmake
            libtinyxml2-dev
            libcurl4-gnutls-dev
      - run:
          name: Make build folder
          command: mkdir build
      - run:
          name: Build library
          command: >
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=Release .. &&
            cmake --build .
